name: Run tests for exercises and fipe

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          
      - name: Install packages
        run: npm install

      - name: Run tests for exercises
        working-directory: ./exercises
        run: npm run test

      - name: Run Cypress tests for fipe
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./fipe
          install: false
          build: npm run build
          start: npm run start
          browser: chrome
