name: Run tests for exercises and fipe

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          
      - name: Install packages
        run: npm install

      - name: Run tests for exercises
        working-directory: ./exercises
        run: npm run test

      - name: Start fipe's Next.js server
        working-directory: ./fipe
        run: |
          npm run build
          npm start &
          SERVER_PID=$!
          sleep 10

      - name: Run fipe's Cypress tests
        working-directory: ./fipe
        uses: cypress-io/github-action@v6
        with:
          browser: chrome

      - name: Stop fipe's Next.js server
        run: |
          kill $SERVER_PID # Kill the server process
